// Screen constants and defines

#if defined(__VIC20__)
#define WINDOW_START 0x1E89
#define WINDOW_LINE2 (WINDOW_START + 22 )
#define WINDOW_LINE3 (WINDOW_START + 44 )
#define WINDOW_LINE4 (WINDOW_START + 66 )
#define WINDOW_LINE5 (WINDOW_START + 110)
#define WINDOW_LINE6 (WINDOW_START + 132)
#define WINDOW_LINE7 (WINDOW_START + 154)
#define WINDOW_LINE8 (WINDOW_START + 176)
#define WINDOW_LINE9 (WINDOW_START + 198)
#define NETWORK_CHAR 0x1FF9
#define NETWORK_CHAR_COLOUR 0x97F9
#endif

#if defined(__C64__)
#define WINDOW_START 0x0400
#define WINDOW_LINE2 (WINDOW_START + 40 )
#define WINDOW_LINE3 (WINDOW_START + 80 )
#define WINDOW_LINE4 (WINDOW_START + 120)
#define WINDOW_LINE5 (WINDOW_START + 160)
#define WINDOW_LINE6 (WINDOW_START + 200)
#define WINDOW_LINE7 (WINDOW_START + 240)
#define WINDOW_LINE8 (WINDOW_START + 280)
#define WINDOW_LINE9 (WINDOW_START + 320)
#define NETWORK_CHAR 0x07E7
#define NETWORK_CHAR_COLOUR 0xDBE7
#endif